[package]
name = "lazap"
version = "0.6.0"
description = "Lazap Launcher"
authors = ["Lazap-Development"]
license = ""
repository = "https://github.com/Lazap-Development/lazap"
default-run = "lazap"
edition = "2021"
rust-version = "1.62.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies.tauri-plugin-sql]
git = "https://github.com/tauri-apps/tauri-plugin-sql"
features = ["sqlite"]

[dependencies.tauri-plugin-fs-extra]
git = "https://github.com/tauri-apps/tauri-plugin-fs-extra"

[dependencies]
serde_json = "1.0.85"
serde = { version = "1.0.144", features = ["derive"] }
tauri = { version = "1.0.5", features = ["devtools", "dialog-all", "fs-create-dir", "fs-read-dir", "fs-read-file", "fs-write-file", "global-shortcut-all", "http-request", "os-all", "path-all", "protocol-asset", "shell-execute", "system-tray", "window-center", "window-close", "window-create", "window-hide", "window-maximize", "window-minimize", "window-print", "window-show", "window-start-dragging", "window-unmaximize", "window-unminimize"] }
window-shadows = "0.1.3"
html_parser = "0.6.3"
thiserror = "*"
whoami = "*"
# openssl = { version = "0.10.41", features = ["vendored"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
