name: CI

on:
  pull_request

jobs:
  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - uses: taiki-e/install-action@v2
      with:
        tool: typos-cli
    - name: Check Formatting
      run: cargo +nightly fmt --all -- --check
    - name: Run Typos
      run: typos

    - name: Prettify code
      uses: creyD/prettier_action@v4.2
      with:
        dry: True
