name: "lazap-nightly-publish"
on:
  workflow_dispatch:

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
          - host: windows-latest
            target: i686-pc-windows-msvc
          - host: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - host: ubuntu-20.04
            target: x86_64-unknown-linux-musl
          - host: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
          - host: ubuntu-20.04
            target: armv7-unknown-linux-gnueabihf
          - host: ubuntu-20.04
            target: aarch64-unknown-linux-musl

    name: ${{ matrix.settings.host }}
    runs-on: ${{ matrix.settings.host }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: ${{ matrix.settings.target }}
    - name: install dependencies (ubuntu only)
      if: matrix.settings.host == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: install app dependencies and build it
      run: yarn && yarn tauri:build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: snapshot-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "Pre-Release v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
